### PR TITLE
added (none) lexer for possible lexers for snippets

### LINKED ISSUE #34: [""] in config.js
при добавлении/редактировании сниппета для пустого лексера `(none)`
в `config.js` сохраняется `[]`, вместо `[""]`
отчего перестают работать сниппеты для пустого лексера `(none)`
что можно сделать?

https://github.com/CudaText-addons/cuda_snippets/blob/master/dlg_snip_manage.py#L571
https://github.com/CudaText-addons/cuda_snippets/blob/master/dlg_snip_manage.py#L573
т.е. `oldlexes` и `newlexs` получаются `[]`, вместо `[""]`

пока что такой неизящный код работает
```
if not oldlexes and not newlexs:
    newlexs.append("")
```

### PR DESCRIPTION
**Pull request by veksha**
fix https://github.com/CudaText-addons/cuda_snippets/issues/34

### CODE REVIEW

**Comment by veksha** [comment]
@ildarkhasanshin @Alexey-T
please, check.

**Comment by Alexey-T** [comment]
but if user already has some snips for the None-lexer, will dialog handle them?

**Comment by veksha** [comment]
They were not supported, as far as I know

**Comment by veksha** [comment]
Maybe there are packages with snippets for none lexer available for download? Needs to be checked

**Comment by veksha** [comment]
if you install "lipsum generator" snippets from "install vscode snippets" dialog, on the next dialog (lexer mapping) you will see nothing on the left side and cudatext lexers on right side. this means "lipsum generator" is not bound to a lexer or filetype, so you can  choose "(none)" and it will just work for none lexers.

"vscode install snippets" dialog had a lot of ui and other bugs. fixed some.

**Comment by Alexey-T** [comment]
Thanks. I will review it soon. @ildarkhasanshin please test.

**Comment by ildarkhasanshin** [comment]
`Add/edit snippets...` выводит
```
Traceback (most recent call last):
  File "/home/ildar/.config/cudatext/py/cuda_snippets/__init__.py", line 97, in show_snipman
    dlg_add = DlgSnipMan(select_lex=lex)
  File "/home/ildar/.config/cudatext/py/cuda_snippets/dlg_snip_manage.py", line 484, in __init__
    self._fill_forms(init_lex_sel=self.select_lex) # select first group with specified lexer if any
  File "/home/ildar/.config/cudatext/py/cuda_snippets/dlg_snip_manage.py", line 540, in _fill_forms
    self._on_group_selected(-1,-1)
  File "/home/ildar/.config/cudatext/py/cuda_snippets/dlg_snip_manage.py", line 754, in _on_group_selected
    self._load_package_snippets(pkg['path'])
  File "/home/ildar/.config/cudatext/py/cuda_snippets/dlg_snip_manage.py", line 1050, in _load_package_snippets
    snips = json.loads(json_data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 320 (char 319)
ERROR: Exception in CudaText for show_snipman: JSONDecodeError: Expecting ',' delimiter: line 1 column 320 (char 319)
```

**Comment by Alexey-T** [comment]
@veksha Module cudax_lib has
`def _json_loads(s, **kw):`
which is better version of your comment trimming...

**Comment by veksha** [comment]
> @veksha Module cudax_lib has `def _json_loads(s, **kw):` which is better version of your comment trimming...

but now we can't deal with "UTF-8 BOM". `_json_loads` eats all exceptions and just prints error in Console.
maybe it can be improved?

**Comment by veksha** [comment]
> `Add/edit snippets...` выводит

@ildarkhasanshin, попробуй с новыми изменениями.

**Comment by Alexey-T** [comment]
> but now we can't deal with "UTF-8 BOM". `_json_loads` eats all exceptions and just prints error in Console. maybe it can be improved?

It was Kvichans' code, maybe try to improve it..

**Comment by ildarkhasanshin** [comment]
> @ildarkhasanshin, попробуй с новыми изменениями.

теперь все ок

**Comment by veksha** [comment]
> > but now we can't deal with "UTF-8 BOM". `_json_loads` eats all exceptions and just prints error in Console. maybe it can be improved?
> 
> It was Kvichans' code, maybe try to improve it..

ok. let's create different issue and close this one?

**Comment by Alexey-T** [comment]
yes. will review in nearest days and apply.

**Pull request merged**
